model:
    arch: unet
data:
    dataset: pascal
    train_split: train_aug
    val_split: val
    img_rows: 512
    img_cols: 512
    path: /content/drive/My Drive/VOCdevkit/VOC2012
    sbd_path: /content/drive/My Drive/benchmark_RELEASE
training:
    train_iters: 300000
    batch_size: 4
    val_interval: 1000
    n_workers: 16
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-3
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume: unet_pascal_best_model.pkl
